apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helpdesk-fe
  namespace: '580452736839'
  selfLink: /apis/serving.knative.dev/v1/namespaces/580452736839/services/helpdesk-fe
  uid: 9519d17e-83c1-4fa9-9046-97fbf602a6fe
  resourceVersion: AAYWTG+XIuA
  generation: 3
  creationTimestamp: '2024-04-17T15:15:57.203529Z'
  labels:
    managed-by: gcp-cloud-build-deploy-cloud-run
    gcb-trigger-id: 9f8a666e-5d7b-4680-b4de-e332e560409c
    gcb-trigger-region: global
    commit-sha: 84c1cdcef1c838b4778065fe854d1a27ca45378c
    gcb-build-id: a4bd0776-1483-4101-bc35-7c2d715fdc2b
    cloud.googleapis.com/location: asia-northeast1
  annotations:
    run.googleapis.com/client-name: gcloud
    serving.knative.dev/creator: puntadewazaid99@gmail.com
    serving.knative.dev/lastModifier: 580452736839-compute@developer.gserviceaccount.com
    run.googleapis.com/client-version: 472.0.0
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/operation-id: f9c2e499-e579-4941-ba8b-f93155cfbc7a
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/minScale: '6'
spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: qxmoppsudh
        managed-by: gcp-cloud-build-deploy-cloud-run
        gcb-trigger-id: 9f8a666e-5d7b-4680-b4de-e332e560409c
        gcb-trigger-region: global
        commit-sha: 84c1cdcef1c838b4778065fe854d1a27ca45378c
        gcb-build-id: a4bd0776-1483-4101-bc35-7c2d715fdc2b
        run.googleapis.com/startupProbeType: Default
      annotations:
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 472.0.0
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 580452736839-compute@developer.gserviceaccount.com
      containers:
      - name: placeholder-1
        image: asia-northeast1-docker.pkg.dev/helpdesk-demo-420516/cloud-run-source-deploy/helpdesk-fe/helpdesk-fe:84c1cdcef1c838b4778065fe854d1a27ca45378c
        ports:
        - name: http1
          containerPort: 3000
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 3000
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 3
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2024-04-17T15:23:25.765344Z'
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2024-04-17T15:15:57.287712Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2024-04-17T15:23:25.729135Z'
  latestReadyRevisionName: helpdesk-fe-00002-bb9
  latestCreatedRevisionName: helpdesk-fe-00002-bb9
  traffic:
  - revisionName: helpdesk-fe-00002-bb9
    percent: 100
    latestRevision: true
  url: https://helpdesk-fe-i5qwuwknwq-an.a.run.app
  address:
    url: https://helpdesk-fe-i5qwuwknwq-an.a.run.app