apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dev-helpdesk-fe
  namespace: '580452736839'
  selfLink: /apis/serving.knative.dev/v1/namespaces/580452736839/services/dev-helpdesk-fe
  uid: 40db4015-d486-41cb-9625-bbc436c6f2fb
  resourceVersion: AAYXrzBViIw
  generation: 6
  creationTimestamp: '2024-04-25T04:05:29.691846Z'
  labels:
    managed-by: gcp-cloud-build-deploy-cloud-run
    gcb-trigger-id: 55b78da8-d803-48b7-8796-1ec21a1cacae
    gcb-trigger-region: global
    commit-sha: afec035e02913966938b1dbce4abd7588407d104
    gcb-build-id: 2ccffe90-d136-44fc-8d3b-157063119d0b
    run.googleapis.com/satisfiesPzs: 'true'
    cloud.googleapis.com/location: asia-southeast1
  annotations:
    run.googleapis.com/client-name: gcloud
    serving.knative.dev/creator: puntadewazaid99@gmail.com
    serving.knative.dev/lastModifier: 580452736839-compute@developer.gserviceaccount.com
    run.googleapis.com/client-version: 474.0.0
    run.googleapis.com/operation-id: 19b85276-fa75-4178-956c-d168dc894799
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/minScale: '0'
    run.googleapis.com/max-surge: '0'
spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: umltolpahb
        managed-by: gcp-cloud-build-deploy-cloud-run
        gcb-trigger-id: 55b78da8-d803-48b7-8796-1ec21a1cacae
        gcb-trigger-region: global
        commit-sha: afec035e02913966938b1dbce4abd7588407d104
        gcb-build-id: 2ccffe90-d136-44fc-8d3b-157063119d0b
        run.googleapis.com/startupProbeType: Default
      annotations:
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 474.0.0
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 580452736839-compute@developer.gserviceaccount.com
      containers:
      - name: placeholder-1
        image: asia-southeast1-docker.pkg.dev/helpdesk-demo-420516/cloud-run-source-deploy/helpdesk-fe/dev-helpdesk-fe:afec035e02913966938b1dbce4abd7588407d104
        ports:
        - name: http1
          containerPort: 3000
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 3000
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 6
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2024-05-05T06:37:37.891468Z'
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2024-04-25T04:05:29.782499Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2024-05-05T06:37:37.854263Z'
  latestReadyRevisionName: dev-helpdesk-fe-00005-pp6
  latestCreatedRevisionName: dev-helpdesk-fe-00005-pp6
  traffic:
  - revisionName: dev-helpdesk-fe-00005-pp6
    percent: 100
    latestRevision: true
  url: https://dev-helpdesk-fe-i5qwuwknwq-as.a.run.app
  address:
    url: https://dev-helpdesk-fe-i5qwuwknwq-as.a.run.app
